resolver: lts-18.21
packages:
 - ./core-data
 - ./core-text
 - ./core-program
 - ./core-telemetry
 - ./core-persistence-postgres
 - ./core-webserver-servant
 - ./core-webserver-warp
 - .
extra-deps:
 - semialign-1.2
 - time-compat-1.9.6.1
 - hashable-1.3.5.0
