resolver: lts-18.16
packages:
 - ./core-data
 - ./core-text
 - ./core-program
 - ./core-telemetry
 - ./core-persistence-postgres
 - .
extra-deps:
 - aeson-2.0.1.0
 - semialign-1.2
 - time-compat-1.9.6.1
 - hashable-1.3.5.0
