name: core-telemetry
version: 0.1.8.1
synopsis: Advanced telemetry
description: |
  This is part of a library to help build command-line programs, both tools and
  longer-running daemons.
  
  This package in particular adds helpers for recording telemetry for
  subsequent analysis. You can instrument your code with tracing and spans,
  and also emit events carrying arbitrary metadata. Backends are provided for
  structured logs, sending traces to observability services, or even just
  outputting the telemetry to console.
  
  See "Core.Telemetry.Observability" to get started.

stability: provisional
license: MIT
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2021-2022 Athae Eredh Siniath and Others
tested-with: GHC == 8.10.7
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: aesiniath/unbeliever

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - template-haskell >= 2.14 && < 3
 - text

library:
  dependencies:
   - async
   - core-text >= 0.3.5
   - core-data >= 0.2.1.11
   - core-program >= 0.3.4
   - chronologique
   - exceptions
   - http-streams
   - io-streams
   - locators
   - mtl
   - random
   - safe-exceptions
   - scientific
   - stm
   - unix
   - uuid
  source-dirs:
  - lib
  exposed-modules:
   - Core.Telemetry
   - Core.Telemetry.Console
   - Core.Telemetry.General
   - Core.Telemetry.Honeycomb
   - Core.Telemetry.Observability
   - Core.Telemetry.Structured
  other-modules: []

extra-doc-files:
  - HoneycombTraceExample.png
